apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-app
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  ports:
  - name: http
    port: 9008
    targetPort: 9008
