logging:
  file: 
    name: target/logs/local_profile_app.log
  level:
    com.mangaement.employee.service: INFO
    com.mangaement.employee.repository: INFO
    com.mangaement.employee.utility: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO

server:
  port: 8098
  
spring:
  application:
    name: report-generation-microservice
  data:
    mongodb:
     database: emp_attendance_management
     uri: ${MONGO_URI:mongodb://my-mongo-db:HkhvoC9X3SE0bPe3yxGnVwrUNssARaDZ2nZhJa2QbsR1kCOoVboPwRIHuYa9qW4RgGPELkn4dZlMACDbUCZ76g==@my-mongo-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@my-mongo-db@}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${JDBC_PASSWORD:shubh123456}
    #url: ${JDBC_URI:jdbc:mysql://googles/emp_attendance_management?cloudSqlInstance=burner-shusinha5:us-central1:my-sql-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=shubh123456&useSSL=false}
    url: jdbc:mariadb://database.c4nar1amqhye.us-east-1.rds.amazonaws.com:3306/emp_attendance_app
    username: ${JDBC_USER:admin}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:14.140.116.145:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
service:
    employee-management: ${EMP_URI:http://employee-tracking-microservice:8088}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
      

