apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeper-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper-app
    spec:
      containers:
        - name: zookeeper-container
          image: jamesmedice/zookeeper:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zookeeper-container