apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper-app
    spec:
      containers:
        - name: zookeeper-container
          image: jamesmedice/zookeeper:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
          ports:
          - containerPort: 2181
            name: http
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zookeeper-container
  selector:
    matchLabels:
     app: zookeeper-app