apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: employee-pod
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-container
          image: shubh1sinha/employee-tracking-microservice:1.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
          ports:
          - containerPort: 8088
            name: http         
  selector:
    matchLabels:
     app: employee-app