server:
  port: 9008
  
spring:
  application:
    name: api-gateway-microservice
    
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-TRACKING-MICROSERVICE
        uri: lb://EMPLOYEE-TRACKING-MICROSERVICE
        predicates:
          - Path=/employee-tracking/**
          
      - id: REPORT-GENERATION-MICROSERVICE
        uri: lb://REPORT-GENERATION-MICROSERVICE
        predicates:
          - Path=/employee-attendance/**
          
      
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       #defaultZone: http://localhost:9098/eureka
       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9098/eureka
debug: true 
