apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  labels:
    app: attendance-app
spec:
  selector:
    app: attendance-app
  type: LoadBalancer
  ports:
  - name: http
    port: 8098
    targetPort: 8098
