logging:
  file: 
    name: target/logs/local_profile_app.log
  level:
    com.mangaement.employee.service: INFO
    com.mangaement.employee.repository: INFO
    com.mangaement.employee.utility: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO

server:
  port: 8088
  
spring:
  application:
    name: employee-tracking-microservice
  data:
    mongodb:
     database: emp_attendance_management
     uri: ${MONGO_URI:mongodb://my-mongo-db:HkhvoC9X3SE0bPe3yxGnVwrUNssARaDZ2nZhJa2QbsR1kCOoVboPwRIHuYa9qW4RgGPELkn4dZlMACDbUCZ76g==@my-mongo-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@my-mongo-db@}

service:
    attendace-management: ${REPORT_URI:http://localhost:8098}
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
