apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: jamesmedice/kafka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: ZOOKEEPER_COTAINER_CONNECT
              value: zookeeper-container:2181


---                  

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: 9092